### ISSUE TITLE
Invoice not showing as Paid

### ISSUE THREAD

**Issue by bmuthig** [bitpay/whmcs-plugin#16]
Received this from BitPay however WHMCS has not updated the invoice as Paid?

Read the docs, am I missing something?

A payment has been fully confirmed by the bitcoin network and applied to your BitPay account settlement.

**Comment by eddiegb** [comment]
I've had the same problem for a few weeks, even opened a ticket with bitpay a few days ago. I've finally had the time today to track down the cause of the problem myself.

I'm afraid this recent commit has broken the IPN functionality of the plugin and introduces a security vulnerability:
https://github.com/bitpay/whmcs-plugin/commit/5d610a347c0adea3922df53e734db00d00895e82

the commit changes the URL passed to the bpCurl function to:
https://'.$network.'bitpay.com/api/invoice/

and introduces some code to figure out what $network should be populated with.

For a live site, $network should become empty, resulting in the url:

https://bitpay.com/api/invoice/

However, what actually happens is that, for a live site, $network becomes the word "live" and the url becomes:

https://livebitpay.com/api/invoice/

And this results in the bpCurl function returning the error "Couldn't resolve host 'livebitpay.com'".  Unfortunately this error message doesn't make it into the WHMCS gateway log, all that gets logged there is "Invoice ID Not Found" and the "Debug data" box is empty. I only discovered it by adding some debugging throughout the plugin to capture return output from various function calls.

So the past few weeks on my site the plugin has been sending a curl request to the non-existent domain livebitpay.com every time a callback came in from Bitpay. 

Thankfully no-one has registered that domain (yet) otherwise they could capture requests to that URL that would expose my API key and other data.

Until Bitpay figure out the fix, I have now just crudely fixed this by modifying the URL in my installation, in two places in modules/gateways/bit-pay/bp_lib.php, to:
https://bitpay.com/api/invoice/

and this fixes the issue for me.

**Comment by ionux** [comment]
Thank you for bringing this to our attention @bmuthig @eddiegb .  I'm fixing the problem now and will have the updated plugin code for you to use in just a few minutes.  Please stand by.

**Comment by ionux** [comment]
Ok, this has been fixed.  Please download and update your plugin with the latest release: https://github.com/bitpay/whmcs-plugin/releases/latest

**Comment by bmuthig** [comment]
Installed new one and the invoice is still not showing up as PAID.  Do I have to test another transaction now or should that one have been marked now?

**Comment by ionux** [comment]
Yes, you'll need to create a new invoice.  The old notificationURL parameter was incorrect so invoices created with that value will still have it.  Any invoice going forward since my fix will be correct, however.

**Comment by bmuthig** [comment]
I just created a new one, received a message from BitPay that it cleared and still not showing up as paid. :(  Can anyone else confirm it's working for them?  Is there anything I possibly need to do re: firewall or something else that could be wrong?

A payment has been fully confirmed by the bitcoin network and applied to your BitPay account settlement.

**Comment by bmuthig** [comment]
Anybody have any suggestions for me here?  About to give up on this?

**Comment by ionux** [comment]
@bmuthig Yep, we are looking at this and will have an answer for you shortly.

**Comment by sambohler** [comment]
@bmuthig, I just peformed a fresh install from master and tried multiple payments using a testnet API Access Key.  "High" Transaction Speed invoices were marked as PAID immediately as they are supposed to.  "Medium" Transaction Speed invoices were marked as PAID after 10ish minutes as they are supposed to.  I didn't test "Low".  What Transaction Speed are you using, and is it happening on both testnet and livenet, or just one of them and if so, which?

**Comment by ionux** [comment]
@bmuthig Can you update your plugin with the latest files from this repository and let us know if you're still having the issue?  The fix was a relatively minor one but it should definitely have taken care of the problem.  If you're having invoice issues it might be something different or maybe server-related.  We'd like to help you get it all working for sure!

**Comment by sambohler** [comment]
@bmuthig, we're going to go ahead and close this issue as we cannot reproduce it.  If you are still having the issue and can provide more details, feel free to reopen it!
