### ISSUE TITLE
payment fails with error Invalid invoice id #0

### ISSUE THREAD

**Issue by zeigerpuppy** [bitpay/whmcs-plugin#25]
I tried accepting a payment with the bitpay plugin (installed from github)
in WHMCS 6.1.
It fails with the following error:
[ERROR] In modules/gateways/bitpay/createinvoice.php: Invalid invoice id #0

Any tips on how to fix the issue?

**Comment by philosodad** [comment]
I haven't run into that error before. Do all other forms of payment work? Are you able to access your error logs?

**Comment by kleetus** [comment]
Is this issue still on-going? I wonder if invoice #0 isn't valid, in general?

**Comment by eignatov** [comment]
I have the same problem with [ERROR] In modules/gateways/bitpay/createinvoice.php: Invalid invoice id #0

Any tips on how to fix the issue?

**Comment by kleetus** [comment]
without more information, I would be speculating here. The issue is that, apparently, the BitPay plugin could not query the database for the invoice.

This is the query for the data:

"SELECT tblinvoices.total, tblinvoices.status, tblcurrencies.code FROM tblinvoices, tblclients, tblcurrencies where tblinvoices.userid = tblclients.id and tblclients.currency = tblcurrencies.id and tblinvoices.id=$invoiceId"

This comes back with no results, so this means that if you didn't change the default join behavior of mysql, this is a left inner join to invoices, clients, and currencies. 

I am not presupposing that this isn't a plugin problem, but I don't have your database. 

So, this is what I would do to figure out the issue really is: 

Is there really an invoice in tblinvoices with the id of 0? This id field should be a INT(10), so doing a test query of:

SELECT * from tblinvoices where id=0 \G

should tell us the answer to this question. If there is an invoice there, maybe the string "0" is being queried for. This would be something I could repair in the plugin or you could ensure this value is an integer. If there isn't a invoice 0, then we need to check the logs to see if the original insertion of this invoice failed and why.

**Comment by eugeneprateek** [comment]
To fix the issue you need to follow the below steps ( It's 10000% working ) 
Make sure you have filled the General Settings >  WHMCS URL and  WHMC SSL URL ( if you have ssl) 

secondly
Go to Paymant gateway pages and then if you see the convert to processing option, just choose USD and save it.
It will fix your issue.

**Comment by kleetus** [comment]
thanks @eugeneprateek
