### ISSUE TITLE
Marked payment as soon as receive a payment

### ISSUE THREAD

**Issue by Hannan-Nozari** [bitpay/whmcs-plugin#40]
Hi there,
We have a problem with Bit-pay. Unfortunately some of the payments takes hours to get confirmed and the module doesn't mark the payments paid till they get confirm however this became an issue for us. We do offer instant activation services and the current configuration is not working with our system so we either have to wait for few hours or accept the orders manually. Is it possible to change something or add a option to mark the payment as paid so our system deliver the product instantly?

It would be a big help for us.

Thanks

**Comment by pieterpoorthuis** [comment]
We have recently seen a small portion of bitcoin transactions being delayed in the bitcoin network. This is outside of BitPay's control, but indeed affects your processing. Since fraudsters are keen to abuse delayed transactions, please make sure to never ship goods or services when the BitPay invoice is in status 'Paid'. An invoice with status ‘Paid’ can easily be reversed by fraudsters. Always wait at least for ‘Confirmed’. For 100% settlement guarantee always wait for ‘Complete’.

The BitPay plugin doesn't allow you to manually override order statuses

**Comment by big89** [comment]
This is a bitpay drawback which should hamper Whmcs customers. Also they can't order products  by quickly paying using bitpay.

**Comment by pieterpoorthuis** [comment]
Merchants can use instant payments. Just make sure that risk mitigation for instant transactions is turned on: https://blog.bitpay.com/advanced-merchant-risk-mitigation/

Most transactions (>95%) can be accepted instantly. Although BitPay contractually agrees to settle Complete transactions (not Paid or Confirmed), we have not seen a Confirmed transaction (with risk mitigation turned on) being reversed.

**Comment by Hannan-Nozari** [comment]
Thank you for the explanation.

Thanks
